<?php

declare(strict_types=1);

namespace Dev\PHPCsFixer\Comment;

use InvalidArgumentException;
use Override;
use PhpCsFixer\ConfigurationException\InvalidForEnvFixerConfigurationException;
use PhpCsFixer\ConfigurationException\RequiredFixerConfigurationException;
use PhpCsFixer\Console\Application;
use PhpCsFixer\Fixer\ConfigurableFixerInterface;
use PhpCsFixer\Fixer\FixerInterface;
use PhpCsFixer\Fixer\WhitespacesAwareFixerInterface;
use PhpCsFixer\FixerConfiguration\DeprecatedFixerOption;
use PhpCsFixer\FixerConfiguration\FixerConfigurationResolver;
use PhpCsFixer\FixerConfiguration\FixerConfigurationResolverInterface;
use PhpCsFixer\FixerConfiguration\FixerOptionBuilder;
use PhpCsFixer\FixerConfiguration\InvalidOptionsForEnvException;
use PhpCsFixer\FixerDefinition\CodeSample;
use PhpCsFixer\FixerDefinition\FixerDefinition;
use PhpCsFixer\FixerDefinition\FixerDefinitionInterface;
use PhpCsFixer\Tokenizer\Analyzer\WhitespacesAnalyzer;
use PhpCsFixer\Tokenizer\Token;
use PhpCsFixer\Tokenizer\Tokens;
use PhpCsFixer\Utils;
use PhpCsFixer\WhitespacesFixerConfig;
use SplFileInfo;
use Symfony\Component\OptionsResolver\Exception\MissingOptionsException;
use Symfony\Component\OptionsResolver\Options;

/**
 * Фиксер обязательных комментариев для всех классов перед class
 *
 * @implements ConfigurableFixerInterface<_AutogeneratedInputConfiguration, _AutogeneratedComputedConfiguration>
 *
 * @phpstan-type _AutogeneratedInputConfiguration array{
 * exclude?: non-empty-list<string>
 * }
 * @phpstan-type _AutogeneratedComputedConfiguration array{
 * exclude: non-empty-list<string>
 * }
 */
final class ClassDocCommentFixer implements FixerInterface, WhitespacesAwareFixerInterface, ConfigurableFixerInterface
{
    private const string EXCLUDE_KEY = 'exclude';

    /**
     * @var array<array-key, mixed>|null
     */
    private ?array $configuration = null;

    private WhitespacesFixerConfig $whitespacesConfig;

    private ?FixerConfigurationResolverInterface $configurationDefinition = null;

    public function __construct()
    {
        $this->whitespacesConfig = $this->getDefaultWhitespacesFixerConfig();
    }

    /**
     * @param array<mixed> $configuration
     */
    #[Override]
    public function configure(array $configuration): void
    {
        foreach ($this->getConfigurationDefinition()->getOptions() as $option) {
            if (!$option instanceof DeprecatedFixerOption) {
                continue;
            }

            $name = $option->getName();
            if (\array_key_exists($name, $configuration)) {
                /**
                 * @psalm-suppress DeprecatedClass
                 * @psalm-suppress InternalClass
                 * @psalm-suppress InternalMethod
                 */
                Utils::triggerDeprecation(new InvalidArgumentException(\sprintf(
                    'Option "%s" for rule "%s" is deprecated and will be removed in version %d.0. %s',
                    $name,
                    $this->getName(),
                    /**
                     * @psalm-suppress InternalClass
                     * @psalm-suppress InternalMethod
                     */
                    Application::getMajorVersion() + 1,
                    str_replace('`', '"', $option->getDeprecationMessage()),
                )));
            }
        }

        try {
            /** @var array<string, mixed> $configuration */
            $this->configuration = $this->getConfigurationDefinition()->resolve($configuration);
        } catch (MissingOptionsException $exception) {
            /**
             * @psalm-suppress InternalClass
             * @psalm-suppress InternalMethod
             */
            throw new RequiredFixerConfigurationException(
                $this->getName(),
                \sprintf('Missing required configuration: %s', $exception->getMessage()),
                $exception,
            );
        } catch (InvalidOptionsForEnvException $exception) {
            /**
             * @psalm-suppress InternalClass
             * @psalm-suppress InternalMethod
             */
            throw new InvalidForEnvFixerConfigurationException(
                $this->getName(),
                \sprintf('Invalid configuration for env: %s', $exception->getMessage()),
                $exception,
            );
        }
    }

    #[Override]
    public function isCandidate(Tokens $tokens): bool
    {
        return $tokens->isAnyTokenKindsFound(Token::getClassyTokenKinds());
    }

    #[Override]
    public function isRisky(): bool
    {
        return false;
    }

    #[Override]
    public function getName(): string
    {
        return \sprintf('ClassDocComment/%s', 'class_doc_comment');
    }

    #[Override]
    public function getDefinition(): FixerDefinitionInterface
    {
        return new FixerDefinition(
            'There must be a class comment before class.',
            [
                new CodeSample(
                    '<?php
final class Sample
{}
',
                ),
            ],
        );
    }

    #[Override]
    public function getPriority(): int
    {
        return -30;
    }

    #[Override]
    public function fix(SplFileInfo $file, Tokens $tokens): void
    {
        if ($tokens->count() <= 0) {
            return;
        }
        if (!$this->isCandidate($tokens)) {
            return;
        }
        if (!$this->supports($file)) {
            return;
        }
        $this->applyFix($file, $tokens);
    }

    #[Override]
    public function supports(SplFileInfo $file): bool
    {
        return true;
    }

    #[Override]
    public function setWhitespacesConfig(WhitespacesFixerConfig $config): void
    {
        $this->whitespacesConfig = $config;
    }

    #[Override]
    public function getConfigurationDefinition(): FixerConfigurationResolverInterface
    {
        if ($this->configurationDefinition === null) {
            $this->configurationDefinition = $this->createConfigurationDefinition();
        }

        return $this->configurationDefinition;
    }

    private function createConfigurationDefinition(): FixerConfigurationResolver
    {
        return new FixerConfigurationResolver([
            (new FixerOptionBuilder(self::EXCLUDE_KEY, 'Excluded class filepath.'))
                ->setAllowedTypes(['string'])
                ->setNormalizer(static function (Options $options, string $value): string {
                    if (trim($value) === '') {
                        return '';
                    }

                    return $value;
                })
                ->getOption(),
        ]);
    }

    /**
     * @return iterable<int>
     */
    private function findClasses(Tokens $tokens): iterable
    {
        for ($index = $tokens->count() - 1; $index > 0; --$index) {
            if (!$tokens[$index]->isClassy()) {
                continue;
            }

            $startIndex = $tokens->getNextTokenOfKind($index, [';']);

            if ($startIndex === null) {
                return;
            }

            yield $startIndex;
        }
    }

    private function applyFix(SplFileInfo $file, Tokens $tokens): void
    {
        /**
         * @var int $index
         * @var Token $token
         */
        foreach ($tokens as $index => $token) {
            if (!$token->isClassy()) {
                continue;
            }

            /** @var int $startBraceIndex */
            $startBraceIndex = $tokens->getNextTokenOfKind($index, ['{']);

            if (!$tokens[$startBraceIndex + 1]->isWhitespace()) {
                continue;
            }

            foreach ($this->findClasses($tokens) as $startIndex) {
                $this->addComment($file, $tokens, $startIndex);
            }
        }
    }

    private function addComment(SplFileInfo $file, Tokens $tokens, int $startIndex): void
    {
        if (!$this->isAllowedByConfiguration($file)) {
            return;
        }

        /** @var int $classIndex */
        $classIndex = $tokens->getPrevTokenOfKind($startIndex, [[T_DECLARE], [T_NAMESPACE]]);

        $docBlockIndex = $this->getDocBlockIndex($tokens, $classIndex);

        if ($this->isPHPDoc($tokens, $docBlockIndex)) {
            return;
        }

        $this->createDocBlock($tokens, $docBlockIndex);
    }

    private function isAllowedByConfiguration(SplFileInfo $file): bool
    {
        if ($this->configuration === null) {
            return true;
        }

        /** @var string $excludeKey */
        $excludeKey = $this->configuration[self::EXCLUDE_KEY];

        return !str_contains($file->getPathname(), $excludeKey);
    }

    private function createDocBlock(Tokens $tokens, int $docBlockIndex): void
    {
        $lineEnd = $this->whitespacesConfig->getLineEnding();

        /** @var int $nextBlockIndex */
        $nextBlockIndex = $tokens->getNextNonWhitespace($docBlockIndex);

        /**
         * @psalm-suppress InternalClass
         * @psalm-suppress InternalMethod
         */
        $originalIndent = WhitespacesAnalyzer::detectIndent($tokens, $nextBlockIndex);
        $toInsert = [
            new Token([T_DOC_COMMENT, '/**'.$lineEnd."{$originalIndent} * TODO: Опиши за что отвечает данный класс, "
                .'какие проблемы решает'.$lineEnd."{$originalIndent} */"]),
            new Token([T_WHITESPACE, $lineEnd.$originalIndent]),
        ];

        /** @var int $index */
        $index = $tokens->getNextMeaningfulToken($docBlockIndex);

        $tokens->insertAt($index, $toInsert);
    }

    private function getDocBlockIndex(Tokens $tokens, int $index): int
    {
        // Иду до объявления final|abstract|interface|enum|trait|class, если по пути встречается атрибут, останавливаюсь на нём
        // Где бы не остановился, отдаю предыдущий индекс, который не является пробелом
        $isAttribute = false;
        do {
            /** @var int $index */
            $index = $tokens->getNextNonWhitespace($index);

            if ($tokens[$index]->getContent() === '#[') {
                $isAttribute = true;

                /** @var int $index */
                $index = $tokens->getPrevNonWhitespace($index);

                break;
            }
        } while (!$tokens[$index]->isGivenKind([T_FINAL, T_ABSTRACT, T_INTERFACE, T_ENUM, T_TRAIT, T_CLASS]));

        if ($isAttribute) {
            return $index;
        }

        /** @var int $prevNonWhitespaceIndex */
        $prevNonWhitespaceIndex = $tokens->getPrevNonWhitespace($index);

        return $prevNonWhitespaceIndex;
    }

    private function isPHPDoc(Tokens $tokens, int $index): bool
    {
        return $tokens[$index]->isGivenKind(T_DOC_COMMENT);
    }

    private function getDefaultWhitespacesFixerConfig(): WhitespacesFixerConfig
    {
        static $defaultWhitespacesFixerConfig = null;

        if ($defaultWhitespacesFixerConfig === null) {
            $defaultWhitespacesFixerConfig = new WhitespacesFixerConfig('    ', "\n");
        }

        /** @var WhitespacesFixerConfig $whiteSpaceConfig */
        $whiteSpaceConfig = $defaultWhitespacesFixerConfig;

        return $whiteSpaceConfig;
    }
}
