openapi: 3.0.3
info:
  title: symfony-starter-kit
  version: 1.0.0
tags:
  - name: profile
    description: Профиль
paths:
  /profile:
    get:
      operationId: profileInfo
      summary: Подробная информация по профилю
      description: Подробная информация по профилю
      tags:
        - profile
      responses:
        '200':
          $ref: '#/components/responses/profileInfo'
        '401':
          $ref: '../common.yaml#/components/responses/authRequired'
        '403':
          $ref: '../common.yaml#/components/responses/forbidden'
    post:
      operationId: saveProfile
      summary: Сохранить профиль
      description: Сохранить профиль
      tags:
        - profile
      requestBody:
        $ref: '#/components/requestBodies/saveProfile'
      responses:
        '200':
          description: Профиль сохранен
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/profileInfo'
        '400':
          $ref: '../common.yaml#/components/responses/invalidRequest'
        '401':
          $ref: '../common.yaml#/components/responses/authRequired'
        '403':
          $ref: '../common.yaml#/components/responses/forbidden'
components:
  requestBodies:
    saveProfile:
      description: Запрос на сохранение профиля
      content:
        application/json:
          schema:
            properties:
              phone:
                type: string
                description: Телефон в профиле
                minLength: 1
                example: '89272222222'
              name:
                type: string
                description: Имя в профиле
                minLength: 1
                example: cazak
            additionalProperties: false
            required:
              - phone
              - name
  responses:
    profileInfo:
      description: Возвращает подробную информацию по профилю
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: '#/components/schemas/profileInfo'
      headers:
        X-Request-TraceId:
          $ref: '../common.yaml#/components/headers/requestTraceId'
  schemas:
    profileInfo:
      type: object
      required:
        - phone
        - name
      additionalProperties: false
      properties:
        phone:
          type: string
          description: Телефон в профиле
          nullable: true
        name:
          type: string
          description: Имя в профиле
          nullable: true
      example: {phone: '89272222222', name: cazak,}

