openapi: 3.0.3
info:
  title: symfony-starter-kit/admin
  version: 1.0.0
tags:
  - name: admin-seo
    description: SEO
paths:
  /admin/seo:
    post:
      operationId: adminSaveSeo
      summary: Сохранить SEO параметры объекта
      description: Сохранить SEO параметры объекта
      tags:
        - admin-seo
      requestBody:
        $ref: '#/components/requestBodies/adminSaveSeo'
      responses:
        '200':
          $ref: '../common.yaml#/components/responses/success'
        '400':
          $ref: '../common.yaml#/components/responses/invalidRequest'
        '401':
          $ref: '../common.yaml#/components/responses/authRequired'
        '403':
          $ref: '../common.yaml#/components/responses/forbidden'
components:
  requestBodies:
    adminSaveSeo:
      description: Запрос на сохранение
      content:
        application/json:
          schema:
            type: object
            properties:
              type:
                type: string
                description: Тип объекта
                enum:
                  - article
                  - task
              identity:
                type: string
                description: Идентификатор объекта
                example: dc8dbada-b154-4ffb-b21c-da70162e2704
              title:
                type: string
                nullable: true
                description: Заголовок
                example: Первая статья
              description:
                type: string
                nullable: true
                description: Описание
                example: Описание первой статьи
              keywords:
                type: string
                nullable: true
                description: Ключевые слова
                example: ключевые слова
            additionalProperties: false
            required:
              - type
              - identity

