framework:
    default_locale: ru
    translator:
        paths:
            - '%kernel.project_dir%/src/Task/translations'
            - '%kernel.project_dir%/src/User/translations'
            - '%kernel.project_dir%/src/Article/translations'
        fallbacks:
            - ru
