openapi: 3.0.3
info:
  title: symfony-starter-kit
  version: 1.0.0
tags:
  - name: article
    description: Статьи
paths:
  /articles:
    get:
      operationId: articleList
      summary: Получить список статей
      description: Получить список статей
      tags:
        - article
      parameters:
        - $ref: '../common.yaml#/components/parameters/limit'
        - $ref: '../common.yaml#/components/parameters/offset'
      security: [ ]
      responses:
        '200':
          $ref: '#/components/responses/articleList'
  /articles/{alias}:
    get:
      operationId: articleInfo
      summary: Получить данные по статье
      description: Получить данные по статье
      tags:
        - article
      security: [ ]
      parameters:
        - in: path
          name: alias
          required: true
          description: Алиас статьи
          example: first-article
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/articleInfo'
        '404':
          $ref: '../common.yaml#/components/responses/notFound'
  /admin/articles:
    get:
      operationId: adminArticleList
      summary: Получить список статей
      description: Получить список статей
      tags:
        - article
      responses:
        '200':
          $ref: '#/components/responses/adminArticleList'
        '401':
          $ref: '../common.yaml#/components/responses/authRequired'
    post:
      operationId: adminArticleCreate
      summary: Создать статью
      description: Создать статью
      tags:
        - article
      requestBody:
        $ref: '#/components/requestBodies/adminArticleCreate'
      responses:
        '200':
          $ref: '#/components/responses/adminArticleCreate'
        '400':
          $ref: '../common.yaml#/components/responses/invalidRequest'
        '401':
          $ref: '../common.yaml#/components/responses/authRequired'
  /admin/articles/{id}:
    get:
      operationId: adminArticleInfo
      summary: Получить информацию по статье
      description: Получить информацию по статье
      tags:
        - article
      parameters:
        - $ref: '#/components/parameters/articleId'
      responses:
        '200':
          $ref: '#/components/responses/adminArticleInfo'
        '401':
          $ref: '../common.yaml#/components/responses/authRequired'
        '404':
          $ref: '../common.yaml#/components/responses/notFound'
    delete:
      operationId: adminArticleRemove
      summary: Удалить статью
      description: Удалить статью
      tags:
        - article
      parameters:
        - $ref: '#/components/parameters/articleId'
      responses:
        '200':
          $ref: '../common.yaml#/components/responses/success'
        '401':
          $ref: '../common.yaml#/components/responses/authRequired'
        '404':
          $ref: '../common.yaml#/components/responses/notFound'
    post:
      operationId: adminArticleUpdate
      summary: Обновить статью
      description: Обновить статью
      tags:
        - article
      parameters:
        - $ref: '#/components/parameters/articleId'
      requestBody:
        $ref: '#/components/requestBodies/adminArticleUpdate'
      responses:
        '200':
          $ref: '#/components/responses/adminArticleUpdate'
        '400':
          $ref: '../common.yaml#/components/responses/invalidRequest'
        '401':
          $ref: '../common.yaml#/components/responses/authRequired'
        '404':
          $ref: '../common.yaml#/components/responses/notFound'
components:
  parameters:
    articleId:
      name: id
      in: path
      required: true
      description: ID статьи
      example: 123e4567-e89b-12d3-a456-426614174000
      schema:
        type: string
        format: uuid
  requestBodies:
    adminArticleCreate:
      description: Запрос на создание статьи
      content:
        application/json:
          schema:
            properties:
              title:
                $ref: '#/components/schemas/articleTitle'
              alias:
                $ref: '#/components/schemas/articleAlias'
              body:
                $ref: '#/components/schemas/articleBody'
            additionalProperties: false
            required:
              - title
              - alias
    adminArticleUpdate:
      description: Запрос на обновление статьи
      content:
        application/json:
          schema:
            properties:
              title:
                $ref: '#/components/schemas/articleTitle'
              alias:
                $ref: '#/components/schemas/articleAlias'
              body:
                $ref: '#/components/schemas/articleBody'
            additionalProperties: false
            required:
              - title
              - alias
  responses:
    articleList:
      description: Возвращает список статей
      content:
        application/json:
          schema:
            type: object
            required:
              - data
              - pagination
              - meta
            properties:
              pagination:
                $ref: '../common.yaml#/components/schemas/pagination'
              meta:
                type: object
                nullable: true
              data:
                type: array
                items:
                  properties:
                    title:
                      type: string
                      description: Заголовок
                    alias:
                      type: string
                      description: Алиас
                    body:
                      type: string
                      description: Контент
                      nullable: true
                example:
                  - title: Первая статья
                    alias: first-article
                    body: Контент первой статьи
                  - title: Вторая статья
                    alias: second-article
                    body: Контент второй статьи
      headers:
        X-Request-TraceId:
          $ref: '../common.yaml#/components/headers/requestTraceId'
    articleInfo:
      description: Возвращает статью
      content:
        application/json:
          schema:
            type: object
            required:
              - data
            properties:
              data:
                type: object
                required:
                  - title
                  - body
                additionalProperties: false
                properties:
                  title:
                    $ref: '#/components/schemas/articleTitle'
                  body:
                    $ref: '#/components/schemas/articleBody'
            example:
              data:
                title: Первая статья
                body: Контент первой статьи
      headers:
        X-Request-TraceId:
          $ref: '../common.yaml#/components/headers/requestTraceId'
    adminArticleList:
      description: Список статей
      content:
        application/json:
          schema:
            type: object
            required:
              - data
              - pagination
              - meta
            properties:
              pagination:
                $ref: '../common.yaml#/components/schemas/pagination'
              meta:
                type: object
                nullable: true
              data:
                type: array
                items:
                  properties:
                    title:
                      type: string
                      description: Заголовок
                    alias:
                      type: string
                      description: Алиас
                    body:
                      type: string
                      description: Контент
                      nullable: true
                example:
                  - title: Первая статья
                    alias: first-article
                    body: Контент первой статьи
                  - title: Вторая статья
                    alias: second-article
                    body: Контент второй статьи
      headers:
        X-Request-TraceId:
          $ref: '../common.yaml#/components/headers/requestTraceId'
    adminArticleCreate:
      description: Статья создана
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/article'
              - $ref: '../common.yaml#/components/schemas/error'
      headers:
        X-Request-TraceId:
          $ref: '../common.yaml#/components/headers/requestTraceId'
    adminArticleInfo:
      description: Информация по статье
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/article'
      headers:
        X-Request-TraceId:
          $ref: '../common.yaml#/components/headers/requestTraceId'
    adminArticleUpdate:
      description: Статья обновлена
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/article'
              - $ref: '../common.yaml#/components/schemas/error'
      headers:
        X-Request-TraceId:
          $ref: '../common.yaml#/components/headers/requestTraceId'
  schemas:
    article:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - title
            - alias
            - createdAt
          properties:
            id:
              type: string
              format: uuid
              description: ID
              example: dc8dbada-b154-4ffb-b21c-da70162e2704
            title:
              $ref: '#/components/schemas/articleTitle'
            alias:
              $ref: '#/components/schemas/articleAlias'
            body:
              type: string
              description: Контент
              example: Контент статьи
              nullable: true
            createdAt:
              $ref: '../common.yaml#/components/schemas/createdAt'
            updatedAt:
              $ref: '../common.yaml#/components/schemas/updatedAt'
        status:
          $ref: '../common.yaml#/components/schemas/succeedStatus'
    articleTitle:
      type: string
      description: Заголовок
      minLength: 1
      example: Первая статья
    articleAlias:
      type: string
      description: Алиас
      minLength: 1
      example: first-article
    articleBody:
      type: string
      description: Контент
      example: Контент первой статьи
      nullable: true

