openapi: 3.0.3
info:
  title: symfony-starter-kit
  version: 1.0.0
tags:
  - name: setting
    description: Настройки
paths:
  /settings:
    get:
      operationId: settingList
      summary: Получить список настроек
      description: Получить список настроек
      tags:
        - setting
      security: [ ]
      responses:
        '200':
          $ref: '#/components/responses/settingList'
  /admin/settings:
    get:
      operationId: adminSettingList
      summary: Получить список настроек
      description: Получить список настроек
      tags:
        - setting
      responses:
        '200':
          $ref: '#/components/responses/adminSettingList'
        '401':
          $ref: '#/components/responses/authRequired'
    post:
      operationId: saveSetting
      summary: Сохранить изменения настройки
      description: Сохранить изменения настройки
      tags:
        - setting
      requestBody:
        $ref: '#/components/requestBodies/saveSetting'
      responses:
        '200':
          $ref: '#/components/responses/success'
        '400':
          $ref: '#/components/responses/invalidRequest'
        '401':
          $ref: '#/components/responses/authRequired'
        '404':
          $ref: '#/components/responses/notFound'
components:
  requestBodies:
    saveSetting:
      description: Запрос на сохранение настройки
      content:
        application/json:
          schema:
            properties:
              type:
                $ref: '#/components/schemas/settingType'
              value:
                $ref: '#/components/schemas/settingValue'
            additionalProperties: false
            required:
              - type
              - value
  responses:
    settingList:
      description: Список настроек
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
                  additionalProperties: false
                  required:
                    - type
                    - value
                  properties:
                    type:
                      $ref: '#/components/schemas/settingType'
                    value:
                      $ref: '#/components/schemas/settingValue'
      headers:
        X-Request-TraceId:
          $ref: '../common.yaml#/components/headers/requestTraceId'
    adminSettingList:
      description: Список настроек
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
                  additionalProperties: false
                  required:
                    - type
                    - value
                    - isPublic
                    - createdAt
                  properties:
                    type:
                      $ref: '#/components/schemas/settingType'
                    value:
                      $ref: '#/components/schemas/settingValue'
                    isPublic:
                      type: boolean
                      description: Публична ли настройка
                    createdAt:
                      $ref: '../common.yaml#/components/schemas/createdAt'
                    updatedAt:
                      $ref: '../common.yaml#/components/schemas/updatedAt'
      headers:
        X-Request-TraceId:
          $ref: '../common.yaml#/components/headers/requestTraceId'
  schemas:
    settingType:
      type: string
      description: Тип настройки
      example: site_name
    settingValue:
      type: string
      description: Значение настройки
      example: symfony-starter-kit

