name: Check Code Quality

on:
    push:
        branches-ignore:
            - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup docker env
        run: ./setup_envs.bash setup-envs && cat .env

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install packages
        run: make composer-install

      - name: Validate all composer rules
        run: make composer-check-all

      - name: Install services
        run: make init

      - name: Validate database mapping
        run: make db-validate

      - name: Check code quality
        run: make lint

      - name: Check difference between OpenApi and application endpoints
        run: make check-openapi-diff

      - name: Check OpenApi schema
        run: docker run --rm -v ${PWD}/backend:/app stoplight/spectral lint /app/src-dev/openapi.yaml -F warn --ruleset=/app/src-dev/.spectral.yaml

      - name: Run functional tests with code coverage
        run: make test-coverage
