name: Check Code Quality

on: [ push ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup docker env
        run: cd ./docker && ./manage.bash setup-envs && cat .env

      - name: Cache Docker env
        id: docker-env-cache
        uses: actions/cache@v3
        with:
          path: docker/.env
          key: docker-env-${{ hashFiles('docker/.env') }}
          restore-keys: |
            docker-env-

      - name: Validate composer.json and composer.lock
        run: cd ./docker && ./manage.bash run-backend composer validate --strict
        env:
          USE_MUTAGEN: 0

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install services
        run: cd ./docker && ./manage.bash install-test

      - name: Check code quality
        run: cd ./docker && ./manage.bash run-backend composer check

      - name: Check difference between OpenApi and application endpoints
        run: cd ./docker && ./manage.bash run-backend bin/console app:openapi-routes-diff ./openapi.yaml

      - name: Run functional tests
        run: cd ./docker && ./manage.bash test
