name: Check Code Quality

on: [ push ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup docker env
        run: ./manage.bash setup-envs && cat .env

      - name: Validate composer.json and composer.lock
        run: ./manage.bash run-backend composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install services
        run: ./manage.bash install-test

      - name: Check packages for known security vulnerabilities
        run: ./manage.bash run-backend composer audit --format=plain

      - name: Check code quality
        run: ./manage.bash run-backend composer check

      - name: Check difference between OpenApi and application endpoints
        run: ./manage.bash run-backend bin/console-dev app:openapi-routes-diff ./openapi.yaml

      - name: Check OpenApi schema
        run: ./manage.bash check-openapi

      - name: Run functional tests
        run: ./manage.bash test
