name: Check Code Quality

on:
    push:
        branches-ignore:
            - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup docker env
        run: ./setup_envs.bash setup-envs && cat .env

      - name: Validate composer.json and composer.lock
        run: make composer-validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install services
        run: make install-test

      - name: Check packages for known security vulnerabilities
        run: make composer-audit

      - name: Check code quality
        run: make lint

      - name: Check difference between OpenApi and application endpoints
        run: make check-openapi-diff

      - name: Check OpenApi schema
        run: docker run --rm -v ${PWD}/backend:/app stoplight/spectral lint /app/src-dev/openapi.yaml -F warn --ruleset=/app/src-dev/.spectral.yaml

      - name: Run functional tests
        run: make test
