name: Check Code Quality

on: [ push ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: cd ./docker && ./manage.bash setup-envs && cat .env

      - name: Cache Docker env
        id: docker-env-cache
        uses: actions/cache@v3
        with:
          path: docker/.env
          key: docker-env-${{ hashFiles('docker/.env') }}
          restore-keys: |
            docker-env-

      - name: Validate composer.json and composer.lock
        run: cd ./docker && ./manage.bash run-backend composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: cd ./docker && ./manage.bash run-backend composer install --prefer-dist --no-progress

      - name: Check code quality
        run: cd ./docker && ./manage.bash run-backend composer check
